services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoSimpleNewsUrls\:
        resource: ../src

    contao_simple_news_urls.routing.router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments:
            - '@router.request_context'
            - '@contao_simple_news_urls.routing.nested_matcher'
            - '@contao_simple_news_urls.routing.route_generator'
            - ''
            - '@event_dispatcher'
            - '@InspiredMinds\ContaoSimpleNewsUrls\Routing\RouteProvider'
        tags:
            - { name: router, priority: 70 }

    contao_simple_news_urls.routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments:
            - '@InspiredMinds\ContaoSimpleNewsUrls\Routing\RouteProvider'
            - '@contao_simple_news_urls.routing.final_matcher'

    contao_simple_news_urls.routing.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments:
            - '@contao_simple_news_urls.routing.dummy_collection'
            - '@contao_simple_news_urls.routing.dummy_context'

    contao_simple_news_urls.routing.dummy_context:
        class: Symfony\Component\Routing\RequestContext

    contao_simple_news_urls.routing.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection

    contao_simple_news_urls.routing.route_generator:
        class: Symfony\Cmf\Component\Routing\ProviderBasedGenerator
        arguments:
            - '@InspiredMinds\ContaoSimpleNewsUrls\Routing\RouteProvider'
            - '@logger'
